language: node_js

node_js:
  - '7' # version of Node.js currently powering electron
  - '8'
  - 'node'

install:
  - yarn global add lerna
  - lerna install

script:
  - yarn test
  - yarn lint-javascript
  - yarn lint-commit-ci

cache: yarn
