language: node_js

node_js:
  - '7' # version of Node.js currently powering electron
  - '8' # current lts
  - '9' # latest

before_script:
  - yarn global add lerna
  - lerna bootstrap

script:
  - yarn test
  - yarn lint-javascript
  - yarn lint-markdown
  - yarn lint-commit-ci

cache: yarn
