environment:
  matrix:
    - nodejs_version: "10"
    - nodejs_version: "12"
    - nodejs_version: "14"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install --global yarn lerna
  - node --version
  - yarn --version
  - lerna --version
  - lerna bootstrap

test_script:
  - yarn test
  - yarn lint-javascript
  - yarn lint-markdown

build: off
